name: 'Verify and Release'

on: workflow_dispatch

permissions: write-all

jobs:
  verify:
    uses: ./.github/workflows/verify.yml
    secrets: inherit
  npm-release:
    uses: ./.github/workflows/npm-release.yml
    secrets: inherit